cc_library(
    name = "http",
    srcs = ["httpclient.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@jsoncpp",
        ]
)

# cc_test(
#     name = "http_client",
#     srcs = ["httpclient_test.cc"],
#     visibility = ["//visibility:public"],
#     deps = [
#         ":http",
#         "@googletest//:gtest_main",
#         ]
# )
