filegroup(
    name = "bootloader_config",
    srcs = ["bootloader_config.cc"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "bootloader",
    srcs = ["bootloader.cc"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//:pub_includes",
        "//src/libaktualizr:config",
        "@jsoncpp",
    ],
)

# cc_test(
#     name = "bootloader_test",
#     srcs = ["bootloader_test.cc"],
#     deps = [
#         ":bootloader",
#         "//:pub_includes",
#         "@googletest//:gtest_main",
#     ],
# )
