cc_library(
    name = "primary",
    srcs = [
        "aktualizr.cc",
        "aktualizr_helpers.cc",
        "provisioner.cc",
        "reportqueue.cc",
        "secondary_provider.cc",
        "sotauptaneclient.cc",
    ],
    hdrs = [
        "aktualizr_helpers.h",
        "provisioner.h",
        "secondary_config.h",
        "secondary_provider_builder.h",
        "sotauptaneclient.h",
    ],
    include_prefix = "primary",
    visibility = ["//visibility:public"],
    deps = [
        "//:pub_includes",
        "//src/libaktualizr/bootstrap",
        "//src/libaktualizr/storage",
        "//src/libaktualizr/uptane",
        "@jsoncpp",
    ],
)

cc_library(
    name = "provisioner_test_utils",
    srcs = ["provisioner_test_utils.cc"],
    hdrs = ["provisioner_test_utils.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":primary",
        "//:pub_includes",
    ],
)

# cc_test(
#     name = "aktualizr",
#     srcs = ["aktualizr_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/crypto:crypto",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@googletest//:gtest_main",
#     ],
#     tags = [],
#     )

# cc_test(
#     name = "reregistration_test",
#     srcs = ["reregistration_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "aktualizr_fullostree_test",
#     srcs = ["aktualizr_fullostree_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = ["manual"],
# )

# cc_test(
#     name = "download_nonostree_test",
#     srcs = ["download_nonostree_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = ["manual", "noptest"],
# )

# cc_test(
#     name = "aktualizr_lite_test",
#     srcs = ["aktualizr_lite_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = ["manual"],
# )

# cc_test(
#     name = "provisioner_test",
#     srcs = ["provisioner_test.cc"],
#     deps = [
#         ":primary",
#         ":provisioner_test_utils",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "reportqueue_test",
#     srcs = ["reportqueue_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "empty_targets_test",
#     srcs = ["empty_targets_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "custom_url_test",
#     srcs = ["custom_url_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "target_mismatch_test",
#     srcs = ["target_mismatch_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "metadata_fetch_test",
#     srcs = ["metadata_fetch_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "metadata_expiration_test",
#     srcs = ["metadata_expiration_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = [],
# )

# cc_test(
#     name = "device_cred_prov_test",
#     srcs = ["device_cred_prov_test.cc"],
#     deps = [
#         ":primary",
#         ":provisioner_test_utils",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = ["crypto"],
# )

# cc_test(
#     name = "uptane_key_test",
#     srcs = ["uptane_key_test.cc"],
#     deps = [
#         ":primary",
#         "//src/libaktualizr/uptane:uptane",
#         "//src/libaktualizr/crypto:crypto",
#         "//src/libaktualizr/utilities:utilities",
#         "//:pub_includes",
#         "//tests:uptane_generator_lib",
#         "//tests:virtual_secondary",
#         "@com_google_googletest//:gtest_main",
#     ],
#     tags = ["crypto"],
# )
