genrule(
    name = "sql_schemas_target",
    srcs = [
        "embed_schemas.py",
        "//:config_dir",
    ],
    outs = ["sql_schemas.cc"],
    cmd = "python3 $(location embed_schemas.py) config/sql $(RULEDIR)/sql_schemas.cc libaktualizr",
)

filegroup(
    name = "storage_config",
    srcs = ["storage_config.cc"],
    visibility = ["//src/libaktualizr:__subpackages__"],
)

cc_library(
    name = "storage",
    srcs = [
        "fsstorage_read.cc",
        "invstorage.cc",
        "sqlstorage.cc",
        "sqlstorage_base.cc",
        "sql_schemas.cc",
    ],
    hdrs = [
        "fsstorage_read.h",
        "sql_utils.h",
        "sqlstorage.h",
        "sqlstorage_base.h",
    ],
    includes = [".."],
    deps = [
        "//src/libaktualizr:config",
        "//:pub_includes",
    ],
    visibility = ["//visibility:public"],
)


# cc_test(
#     name = "storage_atomic",
#     srcs = ["storage_atomic_test.cc"],
#     deps = [
#         ":storage",
#         "//:pub_includes",
#     ],
# )

# cc_test(
#     name = "sql_utils",
#     srcs = ["sql_utils_test.cc"],
#     deps = [
#         ":storage",
#         "//:pub_includes",
#     ],
# )

# cc_test(
#     name = "sqlstorage",
#     srcs = ["sqlstorage_test.cc"],
#     args = [
#         "$(location :test)",
#     ],
#     deps = [
#         ":storage",
#         "//:pub_includes",
#     ],
# )

# cc_test(
#     name = "storage_common",
#     srcs = ["storage_common_test.cc"],
#     deps = [
#         ":storage",
#         "//src/libaktualizr/uptane:uptane_generator_lib",
#         "//src/libaktualizr:config",
#         "//:pub_includes",
#     ],
# )

# sh_test(
#     name = "test_schema_migration",
#     srcs = ["schema_migration_test.sh"],
#     args = [
#         "../../../config/sql",
#     ],
#     tags = ["noptest"],
# )
