cc_library(
    name = "config",
    srcs = [
        "//src/libaktualizr/bootloader:bootloader_config",
        "//src/libaktualizr/package_manager:package_manager_config",
        "//src/libaktualizr/telemetry:telemetry_config",
        "//src/libaktualizr/storage:storage_config",
        "//src/libaktualizr/config:base_config",
    ],
    includes = ["."],
    deps = [
        "//:pub_includes",
        "//src/libaktualizr/utilities:utilities",
        "@jsoncpp"
    ],
    visibility = ["//visibility:public"],
)
AKTUALIZR_DEPS = [
    "//src/libaktualizr/bootloader:bootloader",
    "//src/libaktualizr/bootstrap:bootstrap",
    "//src/libaktualizr/campaign:campaign",
    "//src/libaktualizr/config:primary_config",
    "//src/libaktualizr/crypto:crypto",
    "//src/libaktualizr/http:http",
    "//src/libaktualizr/logging:logging",
    "//src/libaktualizr/package_manager:package_manager",
    "//src/libaktualizr/primary:primary",
    "//src/libaktualizr/storage:storage",
    "//src/libaktualizr/uptane:uptane",
    "//src/libaktualizr/utilities:utilities",
    ":config",
    "//src/libaktualizr-posix/asn1:asn1_lib",
]

cc_library(
    name = "aktualizr_lib",
    deps = AKTUALIZR_DEPS + [
        "@jsoncpp",
        "@curl",
        "@openssl",
        "@boost.thread",
        "@libsodium",
        "@sqlite3",
        "@boost.filesystem",
        "@boost.log",
        "@glib//glib:glib",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "aktualizr",
    hdrs = [":pub_includes"],
    include_prefix = "libaktualizr",
    deps = [":aktualizr_lib"],
    visibility = ["//visibility:public"],
)