cc_library(
    name = "campaign",
    srcs = ["campaign.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@boost.filesystem",
        "@boost.log",
        "@jsoncpp",
    ],
)

# cc_test(
#     name = "campaign_test",
#     srcs = ["campaign_test.cc"],
#     visibility = ["//visibility:public"],
#     deps = [
#         ":campaign",
#         "@googletest//:gtest_main",
#         ]
# )
