filegroup(
    name = "package_manager_config",
    srcs = ["packagemanagerconfig.cc"],
    visibility = ["//src/libaktualizr:__subpackages__"],
)

cc_library(
    name = "package_manager",
    srcs = [
        "ostreemanager.cc",
        "packagemanagerfactory.cc",
        "packagemanagerfake.cc",
        "packagemanagerinterface.cc",
    ],
    hdrs = [
        "packagemanagerfake.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//src/libaktualizr/utilities",
        "@jsoncpp",
        "@ostree",
    ],
)
