name: Aktualizr tests
on:
  pull_request:
    branches: [ dev ]

jobs:
  repo-name:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.repo_name.outputs.repoName }}
    steps:
      - id: repo_name
        run: echo "repoName=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

  on-pull-request:
    runs-on: ubuntu-latest
    needs: repo-name
    container:
      image: ghcr.io/${{needs.repo-name.outputs.output}}/aktualizr-test:dev-image-test-1.0.0
      volumes:
        - ${{ github.workspace }}:/ws

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true 
      
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /ws

      - name: Configure TMPDIR
        run: |
          mkdir -p /ws/tmp
          echo "TMPDIR=/ws/tmp" >> $GITHUB_ENV

      - name: Build Project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug .
          cd build
          make
          make build_tests

      - name: Run ctest excluding 'booted' tests
        run: |
          cd build
          ctest -LE "booted" --output-on-failure


    
    # - name : Run static checks test script
    #   run: sh ./scripts/test_static.sh
    
    # - name : Run make docs test script
    #   run: sh ./scripts/test_docs.sh

    # - name : Run build and install test script
    #   run: sh ./scripts/test_build.sh

    # - name : Run test suite script
    #   run: sh ./scripts/test_testsuite.sh