name: Aktualizr tests
on:
  pull_request:
    branches: [ dev ]

jobs:
  repo-name:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.repo_name.outputs.repoName }}
    steps:
      - id: repo_name
        run: echo "repoName=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

  on-pull-request:
    runs-on: ubuntu-latest
    needs: repo-name
    container:
      image: ghcr.io/${{needs.repo-name.outputs.output}}/aktualizr-test:dev-image-test
      volumes:
        - ${{ github.workspace }}:/ws
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Project
        run: |
          mkdir -p /ws/build && cd /ws/build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make
          make build-tests

      - name: Run ctest excluding 'booted' tests
        run: |
          cd /ws/build
          ctest -LE "booted"

    
    # - name : Run static checks test script
    #   run: sh ./scripts/test_static.sh
    
    # - name : Run make docs test script
    #   run: sh ./scripts/test_docs.sh

    # - name : Run build and install test script
    #   run: sh ./scripts/test_build.sh

    # - name : Run test suite script
    #   run: sh ./scripts/test_testsuite.sh